{% set name = "pycobertura" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycobertura-{{ version }}.tar.gz
  sha256: 34019472da9fcf5ebf33dbb47829d4ab953bcfdfdf42f02b0cebcee4b18e48bf

build:
  entry_points:
    - pycobertura=pycobertura.cli:pycobertura
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-git
    - pip
  run:
    - python >={{ python_min }}
    - click >=4.0
    - jinja2
    - lxml
    - tabulate
    - ruamel.yaml

test:
  imports:
    - pycobertura
  commands:
    - pip check
    - pycobertura --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aconrad/pycobertura
  summary: A Cobertura coverage parser that can diff reports and show coverage progress.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
