{% set name = "pycobertura" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycobertura-{{ version }}.tar.gz
  sha256: b6ef35ac32fdecc5051360f191e38c2288436ea8e7211bc87fb35d26f5257f6c

build:
  entry_points:
    - pycobertura=pycobertura.cli:pycobertura
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-git
    - pip
  run:
    - python >=3.7
    - click >=4.0
    - jinja2
    - lxml
    - tabulate
    - ruamel.yaml

test:
  imports:
    - pycobertura
  commands:
    - pip check
    - pycobertura --help
  requires:
    - pip

about:
  home: https://github.com/aconrad/pycobertura
  summary: A Cobertura coverage parser that can diff reports and show coverage progress.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
